<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	'Name' => array(
		__( 'Name', 'yith-woocommerce-ajax-search' ),
	),
	'Add to cart' => array(
		__( 'Add to cart', 'yith-woocommerce-ajax-search' ),
	),
	'Size' => array(
		__( 'Size', 'yith-woocommerce-ajax-search' ),
	),
	'Small' => array(
		__( 'Small', 'yith-woocommerce-ajax-search' ),
	),
	'Large' => array(
		__( 'Large', 'yith-woocommerce-ajax-search' ),
	),
	'Color' => array(
		__( 'Color', 'yith-woocommerce-ajax-search' ),
	),
	'Label' => array(
		__( 'Label', 'yith-woocommerce-ajax-search' ),
	),
	'Submit search style' => array(
		__( 'Submit search style', 'yith-woocommerce-ajax-search' ),
	),
	'Icon' => array(
		__( 'Icon', 'yith-woocommerce-ajax-search' ),
	),
	'Text' => array(
		__( 'Text', 'yith-woocommerce-ajax-search' ),
	),
	'Icon + Text' => array(
		__( 'Icon + Text', 'yith-woocommerce-ajax-search' ),
	),
	'Price' => array(
		__( 'Price', 'yith-woocommerce-ajax-search' ),
	),
	'Stock' => array(
		__( 'Stock', 'yith-woocommerce-ajax-search' ),
	),
	'SKU' => array(
		__( 'SKU', 'yith-woocommerce-ajax-search' ),
	),
	'Summary' => array(
		__( 'Summary', 'yith-woocommerce-ajax-search' ),
	),
	'Categories' => array(
		__( 'Categories', 'yith-woocommerce-ajax-search' ),
	),
	'Grid' => array(
		__( 'Grid', 'yith-woocommerce-ajax-search' ),
	),
	'List' => array(
		__( 'List', 'yith-woocommerce-ajax-search' ),
	),
	'Price label' => array(
		__( 'Price label', 'yith-woocommerce-ajax-search' ),
	),
	'Pages' => array(
		__( 'Pages', 'yith-woocommerce-ajax-search' ),
	),
	'Placeholder' => array(
		__( 'Placeholder', 'yith-woocommerce-ajax-search' ),
	),
	'Background' => array(
		__( 'Background', 'yith-woocommerce-ajax-search' ),
	),
	'Background focus' => array(
		__( 'Background focus', 'yith-woocommerce-ajax-search' ),
	),
	'Border' => array(
		__( 'Border', 'yith-woocommerce-ajax-search' ),
	),
	'Border focus' => array(
		__( 'Border focus', 'yith-woocommerce-ajax-search' ),
	),
	'Max results to show' => array(
		__( 'Max results to show', 'yith-woocommerce-ajax-search' ),
	),
	'Image' => array(
		__( 'Image', 'yith-woocommerce-ajax-search' ),
	),
	'Image size (px)' => array(
		__( 'Image size (px)', 'yith-woocommerce-ajax-search' ),
	),
	'Image position' => array(
		__( 'Image position', 'yith-woocommerce-ajax-search' ),
	),
	'Show left' => array(
		__( 'Show left', 'yith-woocommerce-ajax-search' ),
	),
	'Show right' => array(
		__( 'Show right', 'yith-woocommerce-ajax-search' ),
	),
	'Popular products' => array(
		__( 'Popular products', 'yith-woocommerce-ajax-search' ),
	),
	'Search products...' => array(
		__( 'Search products...', 'yith-woocommerce-ajax-search' ),
	),
	'No related content found' => array(
		__( 'No related content found', 'yith-woocommerce-ajax-search' ),
	),
	'Overlay Search' => array(
		__( 'Overlay Search', 'yith-woocommerce-ajax-search' ),
	),
	'Add the overlay search block' => array(
		__( 'Add the overlay search block', 'yith-woocommerce-ajax-search' ),
	),
	'Icon settings' => array(
		__( 'Icon settings', 'yith-woocommerce-ajax-search' ),
	),
	'Color Settings' => array(
		__( 'Color Settings', 'yith-woocommerce-ajax-search' ),
	),
	'Color Hover' => array(
		__( 'Color Hover', 'yith-woocommerce-ajax-search' ),
	),
	'Filled Results' => array(
		__( 'Filled Results', 'yith-woocommerce-ajax-search' ),
	),
	'Empty Results' => array(
		__( 'Empty Results', 'yith-woocommerce-ajax-search' ),
	),
	'Overlay Content' => array(
		__( 'Overlay Content', 'yith-woocommerce-ajax-search' ),
	),
	'It is the overlay when click on icon' => array(
		__( 'It is the overlay when click on icon', 'yith-woocommerce-ajax-search' ),
	),
	'Sale!' => array(
		__( 'Sale!', 'yith-woocommerce-ajax-search' ),
	),
	'Settings' => array(
		__( 'Settings', 'yith-woocommerce-ajax-search' ),
	),
	'Enter the label for the search history' => array(
		__( 'Enter the label for the search history', 'yith-woocommerce-ajax-search' ),
	),
	'Please, select the maximum number of the latest searches results' => array(
		__( 'Please, select the maximum number of the latest searches results', 'yith-woocommerce-ajax-search' ),
	),
	'Max latest search items' => array(
		__( 'Max latest search items', 'yith-woocommerce-ajax-search' ),
	),
	'Search input settings' => array(
		__( 'Search input settings', 'yith-woocommerce-ajax-search' ),
	),
	'Enter search placeholder text' => array(
		__( 'Enter search placeholder text', 'yith-woocommerce-ajax-search' ),
	),
	'Border Size' => array(
		__( 'Border Size', 'yith-woocommerce-ajax-search' ),
	),
	'Border radius' => array(
		__( 'Border radius', 'yith-woocommerce-ajax-search' ),
	),
	'Please, select the maximum number of popular searches to show.' => array(
		__( 'Please, select the maximum number of popular searches to show.', 'yith-woocommerce-ajax-search' ),
	),
	'Searches to show' => array(
		__( 'Searches to show', 'yith-woocommerce-ajax-search' ),
	),
	'Grid Layout' => array(
		__( 'Grid Layout', 'yith-woocommerce-ajax-search' ),
	),
	'Please, select the number of columns to show.' => array(
		__( 'Please, select the number of columns to show.', 'yith-woocommerce-ajax-search' ),
	),
	'Columns' => array(
		__( 'Columns', 'yith-woocommerce-ajax-search' ),
	),
	'Please, select the number of rows to show.' => array(
		__( 'Please, select the number of rows to show.', 'yith-woocommerce-ajax-search' ),
	),
	'Rows' => array(
		__( 'Rows', 'yith-woocommerce-ajax-search' ),
	),
	'"No results" text' => array(
		__( '"No results" text', 'yith-woocommerce-ajax-search' ),
	),
	'Content' => array(
		__( 'Content', 'yith-woocommerce-ajax-search' ),
	),
	'Related categories settings' => array(
		__( 'Related categories settings', 'yith-woocommerce-ajax-search' ),
	),
	'Enter the label for the related categories' => array(
		__( 'Enter the label for the related categories', 'yith-woocommerce-ajax-search' ),
	),
	'Please, select the maximum number of related categories to show' => array(
		__( 'Please, select the maximum number of related categories to show', 'yith-woocommerce-ajax-search' ),
	),
	'Max related categories' => array(
		__( 'Max related categories', 'yith-woocommerce-ajax-search' ),
	),
	'Related posts settings' => array(
		__( 'Related posts settings', 'yith-woocommerce-ajax-search' ),
	),
	'Enter the label for the related posts' => array(
		__( 'Enter the label for the related posts', 'yith-woocommerce-ajax-search' ),
	),
	'Show results related to' => array(
		__( 'Show results related to', 'yith-woocommerce-ajax-search' ),
	),
	'Post' => array(
		__( 'Post', 'yith-woocommerce-ajax-search' ),
	),
	'Please, select the maximum number of related posts to show' => array(
		__( 'Please, select the maximum number of related posts to show', 'yith-woocommerce-ajax-search' ),
	),
	'Max related posts' => array(
		__( 'Max related posts', 'yith-woocommerce-ajax-search' ),
	),
	'Background color' => array(
		__( 'Background color', 'yith-woocommerce-ajax-search' ),
	),
	'Search Input' => array(
		__( 'Search Input', 'yith-woocommerce-ajax-search' ),
	),
	'Classic Search' => array(
		__( 'Classic Search', 'yith-woocommerce-ajax-search' ),
	),
	'Add the classic search block' => array(
		__( 'Add the classic search block', 'yith-woocommerce-ajax-search' ),
	),
	'Text and Icon' => array(
		__( 'Text and Icon', 'yith-woocommerce-ajax-search' ),
	),
	'Icon Hover' => array(
		__( 'Icon Hover', 'yith-woocommerce-ajax-search' ),
	),
	'Text Hover' => array(
		__( 'Text Hover', 'yith-woocommerce-ajax-search' ),
	),
	'Text and Icon Hover' => array(
		__( 'Text and Icon Hover', 'yith-woocommerce-ajax-search' ),
	),
	'Background Hover' => array(
		__( 'Background Hover', 'yith-woocommerce-ajax-search' ),
	),
	'Border Hover' => array(
		__( 'Border Hover', 'yith-woocommerce-ajax-search' ),
	),
	'Search icon' => array(
		__( 'Search icon', 'yith-woocommerce-ajax-search' ),
	),
	'Icon on the right' => array(
		__( 'Icon on the right', 'yith-woocommerce-ajax-search' ),
	),
	'Icon on the left' => array(
		__( 'Icon on the left', 'yith-woocommerce-ajax-search' ),
	),
	'Submit Button Label' => array(
		__( 'Submit Button Label', 'yith-woocommerce-ajax-search' ),
	),
	'Enter button label' => array(
		__( 'Enter button label', 'yith-woocommerce-ajax-search' ),
	),
	'Submit Border Radius' => array(
		__( 'Submit Border Radius', 'yith-woocommerce-ajax-search' ),
	),
	'Submit Color Settings' => array(
		__( 'Submit Color Settings', 'yith-woocommerce-ajax-search' ),
	),
	'Product results settings' => array(
		__( 'Product results settings', 'yith-woocommerce-ajax-search' ),
	),
	'Layout' => array(
		__( 'Layout', 'yith-woocommerce-ajax-search' ),
	),
	'Info to show' => array(
		__( 'Info to show', 'yith-woocommerce-ajax-search' ),
	),
	'Product Title Color' => array(
		__( 'Product Title Color', 'yith-woocommerce-ajax-search' ),
	),
	'Limit summary length on/off' => array(
		__( 'Limit summary length on/off', 'yith-woocommerce-ajax-search' ),
	),
	'Summary max words' => array(
		__( 'Summary max words', 'yith-woocommerce-ajax-search' ),
	),
	'Show "View all results" link' => array(
		__( 'Show "View all results" link', 'yith-woocommerce-ajax-search' ),
	),
	'"View all results" text' => array(
		__( '"View all results" text', 'yith-woocommerce-ajax-search' ),
	),
	'Show "On Sale" badge' => array(
		__( 'Show "On Sale" badge', 'yith-woocommerce-ajax-search' ),
	),
	'Show "Out of stock" badge' => array(
		__( 'Show "Out of stock" badge', 'yith-woocommerce-ajax-search' ),
	),
	'Show "Featured" badge' => array(
		__( 'Show "Featured" badge', 'yith-woocommerce-ajax-search' ),
	),
	'Hide "Featured" badge if the product is on sale' => array(
		__( 'Hide "Featured" badge if the product is on sale', 'yith-woocommerce-ajax-search' ),
	),
);